import mongoose from 'mongoose';

// ==========================================
// 1. USER SCHEMA (Role-Based Access Control)
// ==========================================
const userSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  role: {
    type: String,
    enum: ['Citizen', 'DepartmentAdmin', 'SuperAdmin'],
    default: 'Citizen'
  },
  // If role is DepartmentAdmin, assign them to a department
  departmentAssigned: {
    type: String,
    enum: ['Roads', 'Electrical', 'Sanitation', 'Water', 'General'],
    required: function() { return this.role === 'DepartmentAdmin'; }
  },
  // Phone number for verification/spam prevention
  phone: { type: String },
  createdAt: { type: Date, default: Date.now }
});

// ==========================================
// 2. COMPLAINT SCHEMA (Core State Machine & GeoSpatial)
// ==========================================
const complaintSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: { type: String }, // Can be auto-generated by AI if empty
  
  // Reporter mapping
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  
  // AI Classification Data
  category: {
    type: String,
    enum: ['Roads', 'Electrical', 'Sanitation', 'Water', 'General', 'Pending_AI_Review'],
    default: 'Pending_AI_Review'
  },
  aiConfidenceScore: { type: Number, min: 0, max: 100 },
  
  // Media
  imageUrl: { type: String, required: true }, // Cloudinary URL
  resolutionImageUrl: { type: String }, // Uploaded by admin upon fixing
  
  // GeoSpatial Location (Crucial for Map Clustering and Duplicate Detection)
  location: {
    type: { type: String, enum: ['Point'], default: 'Point' },
    coordinates: {
      type: [Number], // [longitude, latitude] format is required by GeoJSON
      required: true
    },
    addressString: { type: String } // E.g., "Ward 4, Main Street"
  },
  
  // State Machine Status
  status: {
    type: String,
    enum: ['Submitted', 'In Review', 'Assigned', 'In Progress', 'Resolved', 'Reopened', 'Rejected'],
    default: 'Submitted'
  },
  
  // Priority Escalation Engine variables
  priorityScore: { type: Number, default: 0 },
  severityRating: { type: Number, default: 1, min: 1, max: 5 }, // Assigned by Gemini Vision
  isEscalated: { type: Boolean, default: false },
  
  // Duplicate Detection & Social Proof
  upvotes: { type: Number, default: 0 },
  linkedDuplicates: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Complaint' }],
  pineconeVectorId: { type: String }, // Links to the embedding stored in Pinecone
  
  // Timeline (Audit trail for admins and citizens)
  timeline: [{
    status: String,
    updatedAt: { type: Date, default: Date.now },
    note: String, // Admin comment, e.g., "Team dispatched"
    updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
  }],

  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now }
});

// Create a 2dsphere index for lightning-fast locality queries ("find near me")
complaintSchema.index({ location: '2dsphere' });

// Auto-update 'updatedAt' field on save
complaintSchema.pre('save', function(next) {
  this.updatedAt = Date.now();
  next();
});

export const User = mongoose.model('User', userSchema);
export const Complaint = mongoose.model('Complaint', complaintSchema);